# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('headline', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('received', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=500)),
                ('rangking', models.IntegerField()),
            ],
        ),
    ]
