# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='code',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
