# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0002_sources_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('url', 'headline')]),
        ),
    ]
