# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0004_auto_20170204_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_news.Sources'),
        ),
    ]
