# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0005_auto_20170204_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=250),
        ),
    ]
