# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0006_auto_20170204_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='rangking',
            field=models.IntegerField(default=0),
        ),
    ]
