# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0008_auto_20170204_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='NA', max_length=250),
        ),
        migrations.AlterField(
            model_name='sources',
            name='author',
            field=models.CharField(default='NA', max_length=250),
        ),
    ]
