# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_news', '0010_remove_sources_rangking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='rangking',
            field=models.IntegerField(default=1),
        ),
    ]
